### Ottieni tutti i film
GET http://localhost:3000/api/films HTTP/1.1

### Ottieni un film specifico per ID
GET http://localhost:3000/api/films/1 HTTP/1.1

### Crea un nuovo film
POST http://localhost:3000/api/films_create/Inception/true/2024-03-21/5 HTTP/1.1
Content-Type: application/json

### Modifica il valore di "favorite" per un film specifico
PUT http://localhost:3000/api/films_favorite/2/true HTTP/1.1
Content-Type: application/json

### Modifica il valore di "favorite" per un film specifico (rimuovere dai preferiti)
PUT http://localhost:3000/api/films/1/favorite/false HTTP/1.1
Content-Type: application/json
###
PUT http://localhost:3000/api/films_mark/1/0 HTTP/1.1
Content-Type: application/json
